# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0003_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
    ]
