# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0006_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
