# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0011_auto_20161110_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='topic',
            new_name='title',
        ),
    ]
