# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0014_auto_20161115_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
