# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0015_auto_20161116_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
    ]
