# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0016_auto_20161116_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
