# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0017_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(max_length=100000),
        ),
    ]
