# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hems_blog', '0018_auto_20161116_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
